'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class View
    
    '''<summary>
    '''kk_aj_CurrentRollid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kk_aj_CurrentRollid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''kk_aj_CurrentPageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kk_aj_CurrentPageType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
